name: cf workers

on:
  workflow_dispatch:
   inputs:
      WORKER_NAME:
        description: "🌟 Name of your worker"
        required: true
        type: string
      DOMAIN_NAME:
        description: "🏠 Name of your domain (not subdomain) at Cloudflare"
        required: true
        type: string
        default: xxx.us.kg
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
